### ISSUE TITLE
Kotlin generation fails with NPE

### ISSUE THREAD

**Issue by dvankley** [plaid/plaid-openapi#102]
Using the [6.1.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.1.0) version of `openapi-generator` with the following command run in Java 17: `java -jar openapi-generator-cli.jar generate -g kotlin -i https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml` I get the following error:

```
[main] INFO  o.o.codegen.TemplateManager - writing file ./src/main/kotlin/org/openapi/models/DepositSwitchGetResponse.kt
Exception in thread "main" java.lang.RuntimeException: Could not generate model 'DepositSwitchGetResponse'
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:563)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:912)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException: Null context for variable '.' on line 14
	at com.samskivert.mustache.Template.getValueIn(Template.java:288)
	at com.samskivert.mustache.Template.getValue(Template.java:224)
	at com.samskivert.mustache.Template.getValueOrDefault(Template.java:279)
	at com.samskivert.mustache.Mustache$VariableSegment.execute(Mustache.java:802)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:881)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:870)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
	at com.samskivert.mustache.Template.executeSegs(Template.java:157)
	at com.samskivert.mustache.Mustache$IncludedTemplateSegment.execute(Mustache.java:774)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$InvertedSegment.execute(Mustache.java:910)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:881)
	at com.samskivert.mustache.Mustache$BlockSegment.executeSegs(Mustache.java:845)
	at com.samskivert.mustache.Mustache$SectionSegment.execute(Mustache.java:866)
	at com.samskivert.mustache.Template.executeSegs(Template.java:157)
	at com.samskivert.mustache.Template.execute(Template.java:134)
	at com.samskivert.mustache.Template.execute(Template.java:125)
	at org.openapitools.codegen.templating.MustacheEngineAdapter.compileTemplate(MustacheEngineAdapter.java:65)
	at org.openapitools.codegen.TemplateManager.write(TemplateManager.java:163)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1058)
	at org.openapitools.codegen.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:1045)
	at org.openapitools.codegen.DefaultGenerator.generateModelDocumentation(DefaultGenerator.java:389)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:560)
	... 4 more
```

and the code generator exits. I also tried with 6.1.1 and 7.0.0 snapshots and got the same result. Any help would be appreciated.

**Comment by phoenixy1** [comment]
I'm not super familiar with OpenAPI generator, but you could try removing the DepositSwitchGetResponse object altogether if it's causing problems. (Deposit Switch isn't currently under active development and never made it out of beta.)

**Comment by dvankley** [comment]
Through the power of lucky guessing I was able to determine that the problem is that that object has an enum with `null` as one of the values. There are a few other objects with the same issue; here's an example from `PayPeriodDetails`:

```
        pay_frequency:
          type: string
          description: The frequency at which an individual is paid.
          enum:
          - PAY_FREQUENCY_UNKNOWN
          - PAY_FREQUENCY_WEEKLY
          - PAY_FREQUENCY_BIWEEKLY
          - PAY_FREQUENCY_SEMIMONTHLY
          - PAY_FREQUENCY_MONTHLY
          - null
          nullable: true
```

Deleting the `- null` at the bottom of the list for all objects that threw errors got codegen to complete.

The way you folks have done it in the Plaid API doc is clearly compliant with [the spec](https://swagger.io/docs/specification/data-models/enums/), so I guess I'll go file an issue with the codegen people.

Thanks for your time.
